absconfig/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('c/', include('contact.urls', namespace='contact')),
    path('', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import *

app_name = 'blog'

urlpatterns = [
    # path('', HomeView.as_view(), name='home'),
    path('', cache_page(60 * 60 * 24)(HomeView.as_view()), name='home'),
    path('p/posts/', AllPostsView.as_view(), name='all_posts'),
    path("search/", SearchResultsView.as_view(), name="search"),
    path('<slug:slug>/', PostListView.as_view(), name='posts'),
    path('comment/<int:pk>/', CreateComment.as_view(), name='create_comment'),
    path('<slug:slug>/<slug:post_slug>', PostDetailView.as_view(), name='post'),
]

templates/blog/include/tags/gallery_tag.html
<section class="hero">
  <div class="hero__slider owl-carousel">
    <div class="hero__item">
      <div class="container-fluid">
        <div class="row">
          {% for photo in photos %}
            <div class="col-lg-6 p-0">
                <div class="hero__inside__item hero__inside__item--wide set-bg"
                     data-setbg="{{ photo.image.url }}">
                </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Hero Section End -->

templates/blog/include/tags/recipes_tag.html
{% load menu_tags %}
                                <li><a href="{% url 'blog:all_posts' %}">Recipes</a>
                                    <div class="header__megamenu__wrapper">
                                        <div class="header__megamenu">
                                            {% for post in last_posts %}
                                            <div class="header__megamenu__item">
                                                <div class="header__megamenu__item--pic set-bg"
                                                    data-setbg="{{ post.image.url }}">
                                                    <div class="label">{{ post.category.name }}</div>
                                                </div>
                                                <div class="header__megamenu__item--text">
                                                    <h5><a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                                                    </h5>
                                                </div>
                                            </div>
                                            {% endfor %}
                                        </div>
                                    </div>
                                </li>

templates/blog/include/tags/top_menu.html
{% load mptt_tags %}

<li class="dropdown">
    <a>Categories</a>
    <ul class="dropdown__menu">
        {% recursetree categories %}
        <li>
            <a href="{{ node.get_absolute_url }}">{{ node.name }}</a>
                {% if not node.is_leaf_node %}
                    <ul class="children">
                        {{ children }}
                    </ul>
                {% endif %}
        </li>
        {% endrecursetree %}
    </ul>
</li>