absconfig/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('c/', include('contact.urls', namespace='contact')),
    path('', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import *

app_name = 'blog'

urlpatterns = [
    # path('', HomeView.as_view(), name='home'),
    path('', cache_page(60 * 60 * 24)(HomeView.as_view()), name='home'),
    path('p/posts/', AllPostsView.as_view(), name='all_posts'),
    path("search/", SearchResultsView.as_view(), name="search"),
    path('<slug:slug>/', PostListView.as_view(), name='posts'),
    path('comment/<int:pk>/', CreateComment.as_view(), name='create_comment'),
    path('<slug:slug>/<slug:post_slug>', PostDetailView.as_view(), name='post'),
]

contact/urls.py
from django.urls import path
from .views import *


app_name = 'contact'

urlpatterns = [
    path('contact', ContactView.as_view(), name='contact'),
    path('about', AboutView.as_view(), name='about'),
    path('feedback', CreateFeedback.as_view(), name='feedback'),
]

templates/include/footer.html
{% load static social_tags cache%}
{% cache 600000 footer %}
    <footer class="footer">
        <div class="container-fluid">
            <div class="footer__instagram">
                <div class="footer__instagram__avatar">
                    <div class="footer__instagram__avatar--pic">
                        <img src="{% static 'img/footer/instagram-avatar.jpg' %}" alt="">
                    </div>
                    <div class="footer__instagram__avatar--text">
                        <h5>@ foodieblog</h5>
                        <span>23,7k follower</span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-2 col-md-2 col-sm-4 col-6">
                        <div class="footer__instagram__item set-bg" data-setbg="{% static 'img/footer/ip-1.jpg' %}"></div>
                    </div>
                    <div class="col-lg-2 col-md-2 col-sm-4 col-6">
                        <div class="footer__instagram__item set-bg" data-setbg="{% static 'img/footer/ip-2.jpg' %}"></div>
                    </div>
                    <div class="col-lg-2 col-md-2 col-sm-4 col-6">
                        <div class="footer__instagram__item set-bg" data-setbg="{% static 'img/footer/ip-3.jpg' %}"></div>
                    </div>
                    <div class="col-lg-2 col-md-2 col-sm-4 col-6">
                        <div class="footer__instagram__item set-bg" data-setbg="{% static 'img/footer/ip-4.jpg' %}"></div>
                    </div>
                    <div class="col-lg-2 col-md-2 col-sm-4 col-6">
                        <div class="footer__instagram__item set-bg" data-setbg="{% static 'img/footer/ip-5.jpg' %}"></div>
                    </div>
                    <div class="col-lg-2 col-md-2 col-sm-4 col-6">
                        <div class="footer__instagram__item set-bg" data-setbg="{% static 'img/footer/ip-6.jpg' %}"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="footer__text">
                        <div class="footer__logo">
                            <a href="#"><img src="img/logo.png" alt=""></a>
                        </div>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
                            ut<br /> labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus
                            commodo viverra<br /> maecenas accumsan lacus vel facilisis. </p>
                        <div class="footer__social">
                                {% get_social_links as socials %}
                                {% for social in socials %}
                                <a href="{{ social.link }} "><img src="{{ social.icon.url }}"></a>
                                {% endfor %}
                        </div>
                    </div>
                    <div class="footer__copyright">
                        <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
{% endcache %}

templates/include/header.html
{% load social_tags cache %}
{% cache 600000 header %}
    <header class="header">
        <div class="header__top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-2 col-md-1 col-6 order-md-1 order-1">
                        <div class="header__humberger">
                            <i class="fa fa-bars humberger__open"></i>
                        </div>
                    </div>
                    <div class="col-lg-8 col-md-10 order-md-2 order-3">

                        {% include 'include/top_nav.html' %}

                    </div>
                    <div class="col-lg-2 col-md-1 col-6 order-md-3 order-2">
                        <div class="header__search">
                            <form action="{% url 'blog:search' %}" method="get">
                              <input name="q" type="text" placeholder="Search...">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endcache %}

templates/include/left_nav.html
{% load menu_tags social_tags cache %}
{% cache 600000 leftnav %}
    <div class="humberger__menu__overlay"></div>
    <div class="humberger__menu__wrapper">
        <div class="humberger__menu__logo">
            <a href="./index.html"><img src="img/humberger/humberger-logo.png" alt=""></a>
        </div>
        <nav class="humberger__menu__nav mobile-menu">
            <ul>
                <li><a href="{% url 'blog:home' %}">Home</a></li>
                {% get_categories %}
                <li><a href="{% url 'contact:about' %}">About</a></li>
                <li><a href="{% url 'contact:contact' %}">Contact</a></li>
            </ul>
        </nav>
        <div id="mobile-menu-wrap"></div>
        <div class="humberger__menu__about">
            <div class="humberger__menu__title sidebar__item__title">
                <h6>About me</h6>
            </div>
            {% get_about as about %}
            <img src="{{ about.images.first.image.url }}" alt="{{ about.images.first.alt }}">
            <p>{{ about.mini_text|safe }}</p>
            <div class="humberger__menu__about__social sidebar__item__follow__links">
                        {% get_social_links as socials %}
                            {% for social in socials %}
                                <a href="{{ social.link }} "><img src="{{ social.icon.url }}" style="max-width: 2%"></a>
                            {% endfor %}
            </div>
        </div>
        <div class="humberger__menu__subscribe">
            <div class="humberger__menu__title sidebar__item__title">
                <h6>Subscribe</h6>
            </div>
            <p>Subscribe to our newsletter and get our newest updates right on your inbox.</p>
            <form action="#">
                <input type="text" class="email-input" placeholder="Your email">
                <label for="agree-check">
                    I agree to the terms & conditions
                    <input type="checkbox" id="agree-check">
                    <span class="checkmark"></span>
                </label>
                <button type="submit" class="site-btn">Subscribe</button>
            </form>
        </div>
    </div>
{% endcache %}

templates/include/sidebar.html
{% load social_tags cache %}
{% cache 600000 sidebar %}

<div class="col-lg-4 col-md-4">
  <div class="sidebar__item">
    <div class="sidebar__about__item">
      <div class="sidebar__item__title">
        <h6>About me</h6>
      </div>
      {% get_about as about %}
      <img src="{{ about.images.first.image.url }}" alt="{{ about.images.first.alt }}">
      <h6>Hi every one! I'm <span>{{ about.name }}</span></h6>
      <p>{{ about.mini_text|safe }}</p>
      <a href="{% url 'contact:about' %}" class="primary-btn">Read more</a>
    </div>
    <div class="sidebar__follow__item">
      <div class="sidebar__item__title">
        <h6>Follow me</h6>
      </div>
      {% get_social_links as social_links %}
      <div class="sidebar__item__follow__links">
        {% for item in social_links %}
          <a href="{{ item.link }}"><img src="{{ item.icon.url }}"></a>
        {% endfor %}
      </div>
    </div>
    <div class="sidebar__item__banner">
      <img src="/static/img/sidebar/banner.jpg" alt="">
    </div>
    <div class="sidebar__item__categories">
      <div class="sidebar__item__title">
        <h6>Categories</h6>
      </div>
    {% include './sidebar_category.html' %}

    </div>
    <div class="sidebar__subscribe__item">
      <div class="sidebar__item__title">
        <h6>Subscribe</h6>
      </div>
      <p>Subscribe to our newsletter and get our newest updates right on your inbox.</p>
      <form action="#">
        <input type="text" class="email-input" placeholder="Your email">
        <label for="s-agree-check">
          I agree to the terms & conditions
          <input type="checkbox" id="s-agree-check">
          <span class="checkmark"></span>
        </label>
        <button type="submit" class="site-btn">Subscribe</button>
      </form>
    </div>
  </div>
</div>
{% endcache %}

templates/include/sidebar_category.html
{% load menu_tags %}
<ul>
  {% get_list_categories as categories %}
  {% for node in categories %}
    <li><a href="{% url 'blog:posts' node.slug %}">{{ node.name }}</a></li>
  {% endfor %}
</ul>

templates/include/top_nav.html
{% load static menu_tags cache %}
                        <nav class="header__menu">
                            <ul>
                                <li class="active"><a href="{% url 'blog:home' %}">Home</a></li>
                                {% get_last_posts %}

                                {% get_categories %}
                                <li><a href="{% url 'contact:about' %}">About</a></li>
                                <li><a href="{% url 'contact:contact' %}">Contact</a></li>
                            </ul>
                        </nav>