absconfig/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('c/', include('contact.urls', namespace='contact')),
    path('', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import *

app_name = 'blog'

urlpatterns = [
    # path('', HomeView.as_view(), name='home'),
    path('', cache_page(60 * 60 * 24)(HomeView.as_view()), name='home'),
    path('p/posts/', AllPostsView.as_view(), name='all_posts'),
    path("search/", SearchResultsView.as_view(), name="search"),
    path('<slug:slug>/', PostListView.as_view(), name='posts'),
    path('comment/<int:pk>/', CreateComment.as_view(), name='create_comment'),
    path('<slug:slug>/<slug:post_slug>', PostDetailView.as_view(), name='post'),
]

blog/models.py
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel


class Category(MPTTModel):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)
    parent = TreeForeignKey('self', related_name='children',
                               on_delete=models.SET_NULL,
                               null=True, blank=True)

    class MPTTMeta:
        order_insertion_by = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:posts', kwargs={'slug': self.slug})


class Tag(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=150)
    image = models.ImageField(upload_to='articles/')
    category = models.ForeignKey(Category, related_name='post',
                                 on_delete=models.SET_NULL,
                                 null=True)
    tags = models.ManyToManyField(Tag, related_name='post')
    author = models.ForeignKey(User, related_name='post',
                               on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    text = models.TextField()
    slug = models.SlugField(max_length=100, unique=True)
    min_read = models.PositiveSmallIntegerField(null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post', kwargs={'slug': self.category.slug,
                                            'post_slug': self.slug})

    def post_min_read(self):
        return f"{self.min_read} min read"


class Recipe(models.Model):
    name = models.CharField(max_length=100)
    serves = models.CharField(max_length=100)
    prep_time = models.PositiveSmallIntegerField(default=0)
    cook_time = models.PositiveSmallIntegerField(default=0)
    ingredients = RichTextField()
    directions = RichTextField()
    post = models.ForeignKey(Post, related_name='recipes',
                             on_delete=models.SET_NULL,
                             null=True, blank=True)
    slug = models.SlugField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class Comment(models.Model):
    name = models.CharField(max_length=60)
    email = models.EmailField(max_length=100)
    website = models.CharField(max_length=100, blank=True, null=True)
    message = models.TextField(max_length=500)
    post = models.ForeignKey(Post, related_name='comments',
                             on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from .models import *


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('created_at', 'post', )
        widgets = {'name': forms.TextInput(attrs={'placeholder': 'Name'}),
                   'email': forms.EmailInput(attrs={'placeholder': 'Email'}),
                   'website': forms.TextInput(attrs={'placeholder': 'Website'}),
                   'message': forms.Textarea(attrs={'placeholder': 'Your message'})}

blog/views.py
from django.db.models import Q, Count
from django.shortcuts import get_object_or_404
from django.views import generic
from .models import *
from .forms import CommentForm


class HomeView(generic.ListView):
    model = Post
    paginate_by = 9
    template_name = 'blog/home.html'
    context_object_name = 'posts'

    def get_queryset(self):
        return Post.objects.all().select_related('category', 'author').order_by('-id')


class PostListView(generic.ListView):
    model = Post
    context_object_name = 'posts'
    paginate_by = 5

    def get_queryset(self):
        return Post.objects.\
            filter(category__slug=self.kwargs.get('slug')). \
            select_related('category', 'author').order_by('-id')

    def get_context_data(self, *, object_list=None, **kwargs):
        posts = Post.objects.\
            filter(category__slug=self.kwargs.get('slug')). \
            select_related('category', 'author')\
            .annotate(number_of_comments=Count('comments'))

        category = Category.objects.get(slug=self.kwargs['slug'])
        context = {'category': category, 'posts': posts}
        return context


class AllPostsView(generic.ListView):
    model = Post
    context_object_name = 'all_posts'
    template_name = 'blog/all_posts.html'
    paginate_by = 5

    def get_queryset(self):
        return Post.objects.\
            all().select_related('category', 'author').order_by('-id')\
            .annotate(number_of_comments=Count('comments'))


class PostDetailView(generic.DetailView):
    model = Post
    slug_url_kwarg = 'post_slug'
    context_object_name = 'post'

    def get_queryset(self):
        return Post.objects.\
            filter(slug=self.kwargs.get('post_slug')).prefetch_related('tags', 'comments').\
            select_related('author', 'category')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post_slug = self.kwargs.get('post_slug')
        post_pk = Post.objects.get(slug=post_slug).pk
        other_posts = Post.objects.filter(Q(pk=post_pk-1)|Q(pk=post_pk+1))\
            .select_related('category')
        context['other_posts'] = other_posts
        print(other_posts)
        context['form'] = CommentForm()
        return context


class CreateComment(generic.CreateView):
    model = Comment
    form_class = CommentForm

    def form_valid(self, form):
        form.instance.post_id = self.kwargs.get('pk')
        self.object = form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return self.object.post.get_absolute_url()


class SearchResultsView(generic.ListView):
    model = Post
    template_name = 'blog/search_results.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        query = self.request.GET.get("q")
        posts = Post.objects.filter(Q(title__icontains=query) |
                                    Q(category__name__icontains=query))\
            .select_related('category', 'author').order_by('-id')\
            .annotate(number_of_comments=Count('comments'))
        context = {'query': self.request.GET.get('q'),
                   'posts': posts}
        return context

templates/blog/all_posts.html
{% extends 'base.html' %}

{% block title %} All Posts {% endblock %}
{% block content %}

    <section class="categories categories-grid spad">
        <div class="categories__post">
            <div class="container">
                <div class="categories__grid__post">
                    <div class="row">
                        <div class="col-lg-8 col-md-8">
                            <div class="breadcrumb__text">
                                <h2>Categories: <span>All</span></h2>
                                <div class="breadcrumb__option">
                                    <a href="{% url 'blog:home' %}">Home</a>
                                    <span>All Posts</span>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                {% for post in all_posts %}
                                    <div class="categories__post__item">
                                        <div class="categories__post__item__pic small__item set-bg"
                                            data-setbg="{{ post.image.url }}">
                                            <div class="post__meta">
                                                <h4>{{ post.created_at|date:"d" }}</h4>
                                                <span>{{ post.created_at|date:"M" }}</span>
                                            </div>
                                        </div>
                                        <div class="categories__post__item__text">
                                            <span class="post__label">{{ post.category }}</span>
                                            <h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
                                            <ul class="post__widget">
                                                <li>by <span>{{ post.author }}</span></li>
                                                <li>{{ post.post_min_read }}</li>
                                                <li>{{ post.number_of_comments }} comment</li>
                                            </ul>
                                            <p>{{ post.text|truncatewords:25 }}</p>
                                        </div>
                                    </div>
                                {% endfor %}
                                </div>
                            </div>


                            {% if page_obj.has_previous or page_obj.has_next %}
                            <div class="pagination">
                                <span class="step-links">
                                    {% if page_obj.has_previous %}
                                        <a href="?page=1">&laquo; first</a>
                                        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                                    {% endif %}

                                    <span class="current">
                                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                                    </span>

                                    {% if page_obj.has_next %}
                                        <a href="?page={{ page_obj.next_page_number }}">next</a>
                                        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                                    {% endif %}
                                </span>
                            </div>
                            {% endif %}

                        </div>
                            {% include 'include/sidebar.html' %}
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/blog/base.html
{% extends 'base.html' %}

{% block title %} Posts {% endblock %}
{% block content %}

    <section class="categories categories-grid spad">
        <div class="categories__post">
            <div class="container">
                <div class="categories__grid__post">
                    <div class="row">
                        <div class="col-lg-8 col-md-8">
                            <div class="breadcrumb__text">
                                <h2>Categories: <span>{{ posts.first.category }}</span></h2>
                                <div class="breadcrumb__option">
                                    <a href="{% url 'blog:home' %}">Home</a>
                                    <span>{{ posts.first.category }}</span>
                                </div>
                            </div>
                            <div class="row">
                                {% for post in posts %}
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    <div class="categories__post__item">
                                        <div class="categories__post__item__pic small__item set-bg"
                                            data-setbg="{{ post.image.url }}">
                                            <div class="post__meta">
                                                <h4>{{ post.created_at|date:"d" }}</h4>
                                                <span>{{ post.created_at|date:"M" }}</span>
                                            </div>
                                        </div>
                                        <div class="categories__post__item__text">
                                            <span class="post__label">{{ post.category }}</span>
                                            <h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
                                            <ul class="post__widget">
                                                <li>by <span>{{ post.author }}</span></li>
                                                <li>3 min read</li>
                                                <li>20 Comment</li>
                                            </ul>
                                            <p>{{ post.text|truncatewords:25 }}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                                {% endfor %}
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/blog/home.html
{% extends 'base.html' %}
{% load gallery_tags %}
{% block title %} All Posts {% endblock %}

{% block content %}

{% get_gallery %}
    <!-- Categories Section Begin -->
    <section class="categories spad">
        <div class="categories__post">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-md-8">
                        {% for post in posts %}
                        {% if forloop.counter == 1 %}
                                <div class="categories__post__item categories__post__item--large">
                                    <div class="categories__post__item__pic set-bg"
                                        data-setbg="{{ post.image.url }}">
                                        <div class="post__meta">
                                            <h4>{{ post.created_at|date:"d" }}</h4>
                                            <span>{{ post.created_at|date:"M" }}</span>
                                        </div>
                                    </div>
                                    <div class="categories__post__item__text">
                                        <ul class="post__label--large">
                                            {% for tag in post.tags.all %}
                                            <li>{{ tag.name }}</li>
                                            {% endfor %}
                                        </ul>
                                        <h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
                                        <ul class="post__widget">
                                            <li>by <span>{{ post.author }}</span></li>
                                            <li>{{ post.post_min_read }}</li>
                                            <li>{{ post.get_comments.count }} comment</li>
                                        </ul>
                                        <p>{{ post.text|truncatewords:25 }}</p>
                                        <a href="{{ post.get_absolute_url }}" class="primary-btn">Read more</a>
                                        <div class="post__social">
                                            <span>Share</span>
                                            <a href="#"><i class="fa fa-facebook"></i> <span>82</span></a>
                                            <a href="#"><i class="fa fa-twitter"></i> <span>24</span></a>
                                            <a href="#"><i class="fa fa-envelope-o"></i> <span>08</span></a>
                                        </div>
                                    </div>
                                </div>
                        {% endif %} {% endfor %}
                                <div class="row">
                                    <div class="col-lg-6 col-md-6 col-sm-6">
                                        {% for post in posts %}
                                            {% if forloop.counter > 1 and forloop.counter <= 5 %}
                                                <div class="categories__post__item">
                                                    <div class="categories__post__item__pic small__item set-bg"
                                                        data-setbg="{{ post.image.url }}">
                                                        <div class="post__meta">
                                                            <h4>{{ post.created_at|date:"d" }}</h4>
                                                            <span>{{ post.created_at|date:"M" }}</span>
                                                        </div>
                                                    </div>
                                                    <div class="categories__post__item__text">
                                                        <span class="post__label">{{ post.category }}</span>
                                                        <h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
                                                        <ul class="post__widget">
                                                            <li>by <span>{{ post.author }}</span></li>
                                                            <li>3 min read</li>
                                                            <li>20 Comment</li>
                                                        </ul>
                                                        <p>{{ post.text|truncatewords:25 }}</p>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-lg-6 col-md-6 col-sm-6">
                                                {% elif forloop.counter > 5 %}
                                                <div class="categories__post__item">
                                                    <div class="categories__post__item__pic smaller__large set-bg"
                                                        data-setbg="{{ post.image.url }}">
                                                        <div class="post__meta">
                                                            <h4>{{ post.created_at|date:"d" }}</h4>
                                                            <span>{{ post.created_at|date:"M" }}</span>
                                                        </div>
                                                    </div>
                                                    <div class="categories__post__item__text">
                                                        <span class="post__label">{{ post.category }}</span>
                                                        <h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                                                        </h3>
                                                        <ul class="post__widget">
                                                            <li>by <span>{{ post.author }}</span></li>
                                                            <li>3 min read</li>
                                                            <li>20 Comment</li>
                                                        </ul>
                                                        <p>{{ post.text|truncatewords:25 }}</p>
                                                    </div>
                                                </div>
                                            {% endif %}
                                        {% endfor %}
                                    </div>
                                </div>
                        {% if page_obj.has_previous or page_obj.has_next %}
                            <div class="pagination">
                                <span class="step-links">
                                    {% if page_obj.has_previous %}
                                        <a href="?page=1">&laquo; first</a>
                                        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                                    {% endif %}

                                    <span class="current">
                                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                                    </span>

                                    {% if page_obj.has_next %}
                                        <a href="?page={{ page_obj.next_page_number }}">next</a>
                                        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                                    {% endif %}
                                </span>
                            </div>
                            {% endif %}
                        </div>
                    {% include 'include/sidebar.html' %}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/blog/post_detail.html
{% extends 'base.html' %}
{% load social_tags %}
{% block title %} {{ post.title }} {% endblock %}
{% block content %}
    <!-- Single Post Section Begin -->
    <section class="single-post spad">
        <div class="single-post__hero set-bg" data-setbg="{{ post.image.url }}"></div>
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-lg-8">
                    <div class="single-post__title">
                        <div class="single-post__title__meta">
                            <h2>{{ post.created_at|date:"d" }}</h2>
                            <span>{{ post.created_at|date:"M" }}</span>
                        </div>
                        <div class="single-post__title__text">
                            <ul class="label">
                                {% for tag in post.tags.all %}
                                <li>{{ tag.name }}</li>
                                {% endfor %}
                            </ul>
                            <h4>{{ post.title }}</h4>
                            <ul class="widget">
                                <li>by {{ post.author }}</li>
                                <li>{{ post.post_min_read }}</li>
                                <li>{{ post.get_comments.count }}</li>
                            </ul>
                        </div>
                    </div>
                    <div class="single-post__top__text">
                        <p>{{ post.text|truncatewords:250 }}</p>
                    </div>
                    <div class="single-post__recipe__details">
                        {% for recipe in post.recipes.all %}
                                                <h2>{{ recipe.name }}</h2>
                        <div class="single-post__recipe__details__option">
                            <ul>
                                <li>
                                    <h5><i class="fa fa-user-o"></i> SERVES</h5>
                                    <span>{{ recipe.serves }}</span>
                                </li>
                                <li>
                                    <h5><i class="fa fa-clock-o"></i> PREP TIME</h5>
                                    <span>{{ recipe.prep_time }}</span>
                                </li>
                                <li>
                                    <h5><i class="fa fa-clock-o"></i> Cook TIME</h5>
                                    <span>{{ recipe.cook_time }}</span>
                                </li>
                                <li><a href="#" class="primary-btn"><i class="fa fa-print"></i> Read more</a></li>
                            </ul>
                        </div>

                        <div class="single-post__recipe__details__indegradients">
                            <h5>Ingredients</h5>
                                {{ recipe.ingredients|safe }}
                        </div>
                        <div class="single-post__recipe__details__direction">
                            <h5>Directions</h5>
                                {{ recipe.directions|safe }}
                        </div>
                        {% endfor %}
                    </div>


                    <div class="single-post__desc">
                        {{ post.text|truncatewords:250 }}
                    </div>

                    <div class="single-post__tags">
                        {% for tag in post.tags.all %}
                        <a href="#">{{ tag.name }}</a>
                        {% endfor %}
                        </div>
                    {% for other_post in other_posts %}
                    {% if forloop.counter == 1 %}
                    <div class="single-post__next__previous">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <a href="{{ other_post.get_absolute_url }}" class="single-post__previous">
                                    <h6><span class="arrow_carrot-left"></span> Previous post</h6>
                                    <div class="single-post__previous__meta">
                                        <h4>{{ other_post.created_at|date:"d" }}</h4>
                                        <span>{{ other_post.created_at|date:"M" }}</span>
                                    </div>
                                    <div class="single-post__previous__text">
                                        <span>{{ other_post.category}}</span>
                                        <h5>{{ other_post.title }}</h5>
                                    </div>
                                </a>
                            </div>
                            {% else %}
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <a href="{{ other_post.get_absolute_url }}" class="single-post__next">
                                    <h6>Next post <span class="arrow_carrot-right"></span> </h6>
                                    <div class="single-post__next__meta">
                                        <h4>{{ other_post.created_at|date:"d" }}</h4>
                                        <span>{{ other_post.created_at|date:"M" }}</span>
                                    </div>
                                    <div class="single-post__next__text">
                                        <span>{{ other_post.category}}</span>
                                        <h5>{{ other_post.title }}</h5>
                                    </div>
                                </a>
                            </div>
                        {% endif %}
                    </div>
                    </div>
                    {% endfor %}
                    <div class="single-post__author__profile">
                        {% get_about as about %}
                        <div class="single-post__author__profile__pic">
                            <img src="img/categories/single-post/author-profile.jpg" alt="">
                        </div>
                        <div class="single-post__author__profile__text">
                            <h4>{{ about.name }}</h4>
                            <p>{{ about.mini_text|safe }}</p>
                            {% get_social_links as socials %}
                            <div class="single-post__author__profile__social">
                                {% for social in socials %}
                                <a href="{{ social.link }}"><img src="{{ social.icon.url }}"></a>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <div class="single-post__comment">
                        <div class="widget__title">
                            <h4>{{ post.get_comments.count }} comment</h4>
                        </div>
                        {% for comment in post.comments.all %}
                        <div class="single-post__comment__item">
                            <div class="single-post__comment__item__pic">
                                <img src="img/categories/single-post/comment/comment-1.jpg" alt="">
                            </div>
                            <div class="single-post__comment__item__text">
                                <h5>{{ comment.name }}</h5>
                                <span>{{ comment.created_at|date:"d M Y"}}</span>
                                <p>{{ comment.message }}</p>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    <div class="single-post__leave__comment">
                        <div class="widget__title">
                            <h4>Leave a comment</h4>
                        </div>
                        <form action="{% url 'blog:create_comment' post.pk %}" method="post">
                            <div class="input-list">
                                {% csrf_token %}
                                {{ form.name }}
                                {{ form.email }}
                                {{ form.website }}
                            </div>
                                {{ form.message }}
                            <button type="submit" class="site-btn">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Single Post Section End -->
{% endblock %}