absconfig/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('c/', include('contact.urls', namespace='contact')),
    path('', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import *

app_name = 'blog'

urlpatterns = [
    # path('', HomeView.as_view(), name='home'),
    path('', cache_page(60 * 60 * 24)(HomeView.as_view()), name='home'),
    path('p/posts/', AllPostsView.as_view(), name='all_posts'),
    path("search/", SearchResultsView.as_view(), name="search"),
    path('<slug:slug>/', PostListView.as_view(), name='posts'),
    path('comment/<int:pk>/', CreateComment.as_view(), name='create_comment'),
    path('<slug:slug>/<slug:post_slug>', PostDetailView.as_view(), name='post'),
]

contact/urls.py
from django.urls import path
from .views import *


app_name = 'contact'

urlpatterns = [
    path('contact', ContactView.as_view(), name='contact'),
    path('about', AboutView.as_view(), name='about'),
    path('feedback', CreateFeedback.as_view(), name='feedback'),
]

contact/models.py
from ckeditor.fields import RichTextField
from django.db import models


class ContactModel(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)
    website = models.URLField(null=True, blank=True)
    message = models.TextField(max_length=2000)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name} - {self.email}"


class ContactLink(models.Model):
    icon = models.FileField(upload_to='icons/')
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class About(models.Model):
    name = models.CharField(max_length=50, null=True)
    text = RichTextField()
    mini_text = RichTextField()

    def __str__(self):
        return self.name


class AboutImage(models.Model):
    image = models.ImageField(upload_to='about/')
    page = models.ForeignKey(About, on_delete=models.CASCADE,
                             related_name='images')
    alt = models.CharField(max_length=100, null=True)

    def __str__(self):
        return str(self.pk)


class Social(models.Model):
    icon = models.FileField(upload_to='icons/')
    name = models.CharField(max_length=200)
    link = models.URLField()

    def __str__(self):
        return self.name

contact/forms.py
from django import forms
from .models import *


class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactModel
        fields = '__all__'

contact/views.py
from django.shortcuts import render

from .forms import ContactForm
from django.views import generic
from .models import *


class ContactView(generic.View):
    def get(self, request):
        contacts = ContactLink.objects.all()
        form = ContactForm()
        return render(request, 'contact/contact.html', {'contacts': contacts, 'form': form})


class CreateFeedback(generic.CreateView):
    form_class = ContactForm
    success_url = '/'


class AboutView(generic.View):
    def get(self, request):
        about = About.objects.last()
        return render(request, 'contact/about.html', {'about': about})

templates/contact/about.html
{% extends 'base.html' %}
{% load social_tags %}
{% block title %} About Us {% endblock %}

{% block content %}

    <section class="about spad">
        <div class="container">
            <div class="about__text">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="breadcrumb__text">
                            <h2>About me</h2>
                            <div class="breadcrumb__option">
                                <a href="{% url 'blog:home' %}">Home</a>
                                <span>About</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-6">
                        <div class="about__pic__item__large">
                            <img src="{{ about.images.first.image.url }}" alt="{{about.images.first.alt}}">
                        </div>
                        <div class="about__pic">
                            {% for image in about.images.all %}
                            {% if forloop.counter > 1 %}
                            <div class="about__pic__item">
                                <img src="{{ image.image.url }}" alt="{{ image.alt }}">
                            </div>
                            {% endif %} {% endfor %}
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="about__right__text">
                            {{ about.text|safe }}
                            <div class="about__right__text__social">
                                {% get_social_links as socials %}
                                {% for social in socials %}
                                <a href="{{ social.link }} "><img src="{{ social.icon.url }}"></a>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/contact/contact.html
{% extends 'base.html' %}
{% block title %} Contact Us {% endblock %}
{% block content %}
    <section class="contact spad">
        <div class="container">
            <div class="contact__text">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="breadcrumb__text">
                            <h2>Contact</h2>
                            <div class="breadcrumb__option">
                                <a href="{% url 'blog:home' %}">Home</a>
                                <span>Contact</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-6 col-md-6">
                        <div class="contact__map">
                            <iframe
                                src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d96748.5538666784!2d-74.25209557318462!3d40.73139236772185!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c25370329a0e1d%3A0xe1bcdc2adcfee473!2sNewark%2C%20NJ%2C%20USA!5e0!3m2!1sen!2sbd!4v1585643782289!5m2!1sen!2sbd"
                                height="350" style="border:0;" allowfullscreen="" aria-hidden="false"
                                tabindex="0"></iframe>
                        </div>
                        <div class="contact__widget">
                            <ul>
                                {% for contact in contacts %}
                                <li>
<!--                                    <i class="fa fa-map-marker"></i>-->
                                    <img src="{{ contact.icon.url }}" class="contact_icon">
                                    <span>{{ contact.name }}</span>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <div class="contact__form">
                            <div class="contact__form__title">
                                <h2>gET IN TOUCH</h2>
                                <p>My experience with Realy is absolutely positive. The themes are beautifully designed
                                    and well documented. Realy theme provides quick support.</p>
                            </div>
                            <form action="{% url 'contact:feedback' %}" method="post">
<!--                                <input type="text" placeholder="Name">-->
<!--                                <input type="text" placeholder="Email">-->
<!--                                <input type="text" placeholder="Website">-->
<!--                                <textarea placeholder="Message"></textarea>-->
                                {% csrf_token %}
                                {{ form }}
                                <button type="submit" class="site-btn">Submit</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}